version: '3'
services:
  backend:
    image: registry.cn-shanghai.aliyuncs.com/hooz/nav:backend
    container_name: znav-backend
    environment:
      - DB_USER=root       # 数据库用户
      - DB_PASSWORD=123456 # 数据库密码
      - DB_HOST=mysql  # 数据库容器
      - DB_PORT=3306   # 数据库端口
      - DB_NAME=znav   # zanv数据库
      - JWT_SECRET=supersecret
    ports:
      - "8080:8080"  # 暴露后端的 8080 端口
    networks:
      - znav_network
    depends_on:
      - mysql  # 等待 MySQL 启动
    restart: always

  frontend:
    image: registry.cn-shanghai.aliyuncs.com/hooz/nav:frontend
    container_name: znav-frontend
    ports:
      - "80:80"  # 暴露前端的 80 端口
    depends_on:
      - backend  # 等待 backend 服务启动
    networks:
      - znav_network
    restart: always

  mysql:
    image: mysql:8.4.0-oraclelinux8
    container_name: znav-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=znav
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - znav_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    restart: always

networks:
  znav_network:
    driver: bridge
