version: '3'
services:
  backend:
    image: registry.cn-shanghai.aliyuncs.com/hooz/nav:backend
    container_name: znav-backend
    environment:
      - DB_USER=postgres       # 数据库用户
      - DB_PASSWORD=postgres   # 数据库密码
      - DB_HOST=postgres  # 数据库容器
      - DB_PORT=5432     # 数据库端口
      - DB_NAME=znav     # znav数据库
      - JWT_SECRET=supersecret
    ports:
      - "8080:8080"  # 暴露后端的 8080 端口
    networks:
      - znav_network
    depends_on:
      - postgres  # 等待 PostgreSQL 启动
    restart: always

  frontend:
    image: registry.cn-shanghai.aliyuncs.com/hooz/nav:frontend
    container_name: znav-frontend
    ports:
      - "80:80"  # 暴露前端的 80 端口
    depends_on:
      - backend  # 等待 backend 服务启动
    networks:
      - znav_network
    restart: always

  postgres:
    image: postgres:16
    container_name: znav-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=znav
      - TZ=Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - znav_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 3
    restart: always

networks:
  znav_network:
    driver: bridge
